version: 2

sources:
  - name: medical_data  
    database: projet4a  
    schema: airbyte_schema  
    tables:
      - name: cardio_train
      - name: healthcare_dataset
      - name: heart
      - name: hospital_readmissions
      - name: mental_health_dataset
      
